### ISSUE TITLE
Clarification on parameters

### ISSUE THREAD

**Issue by rspreafico** [endrebak/epic2#4]
```
--fragment-size (Single end reads only) Size of the sequenced fragment. The center of the the fragment will be taken as half the fragment size. Default 150
```

Would it be easier to pass the actual fragment size as IP'ed and seen on a gel/TapeStation?

```
--effective-genome-fraction
```
When `--genome` is passed, this does not seem set by default. However, in e.g. `MACS2`, passing a genome uses automatically the effective genome fraction.

```
--drop-duplicates
```

The flag name seems to suggest that duplicates are dropped when the flag is set, however the parameter seems to do the opposite of what the name suggests

```
Keep reads mapping to the same position on the same strand within a library. Default is to remove all but the first duplicate.
```

**Comment by endrebak** [comment]
Thanks. 

For 1 I do not know what you mean, embarrassingly. I am not a wet-lab biologist though.

2. When using --genome the egf should be automatically selected. This is a bug then.

3. This is a bug in the docs, not the tool/flag.

I'll look into all of these tomorrow :) Thanks for reporting.

**Comment by endrebak** [comment]
With the latest merge, the two last issues should have been fixed. I think I undrestand what you mean with the first. 

```
                        (Single end reads only) Size of the
                        fragment. The center of the the fragment will be taken
                        as half the fragment size. Default 150.

```

Is correct no? Just remove sequenced, which is wrong.

**Comment by rspreafico** [comment]
Thanks, yes that sounds more correct. Residual question: what does this mean?

```
The center of the the fragment will be taken as half the fragment size
```

**Comment by endrebak** [comment]
Hmm. Should probably mean "each read is extended half the fragment size from the 5' end" :) 

Thanks for bothering to ask such questions :)

**Comment by endrebak** [comment]
I would recommend you dl the newest version from PyPI (`pip install epic2 == 0.0.3`) and redo your analyses. I have implemented several bugfixes :) Sorry for the inconvenience.
